
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLLECTION COLON COMMA CREATE DATABASE DELETE DOCUMENTS FALSE FROM GET IDENTIFIER INSERT INTO LBRACE NULL NUMBER RBRACE SET STRING TRUE UPDATE WHERE WITHstatement : create_db\n                 | create_collection\n                 | insert_document\n                 | get_documents\n                 | update_document\n                 | delete_document\n                 | delete_collectioncreate_db : CREATE DATABASE IDENTIFIER WITH COLLECTION IDENTIFIERcreate_collection : CREATE COLLECTION IDENTIFIER INTO DATABASE IDENTIFIERinsert_document : INSERT LBRACE document RBRACE INTO DATABASE IDENTIFIER COLLECTION IDENTIFIERget_documents : GET DOCUMENTS FROM DATABASE IDENTIFIER COLLECTION IDENTIFIERupdate_document : UPDATE LBRACE document RBRACE WHERE LBRACE document RBRACE INTO DATABASE IDENTIFIER COLLECTION IDENTIFIER delete_document : DELETE LBRACE document RBRACE FROM DATABASE IDENTIFIER COLLECTION IDENTIFIERdelete_collection : DELETE COLLECTION IDENTIFIER FROM DATABASE IDENTIFIERdocument : STRING COLON value\n                | document COMMA STRING COLON valuevalue : STRING\n             | NUMBER\n             | TRUE\n             | FALSE\n             | NULL'
    
_lr_action_items = {'CREATE':([0,],[9,]),'INSERT':([0,],[10,]),'GET':([0,],[11,]),'UPDATE':([0,],[12,]),'DELETE':([0,],[13,]),'$end':([1,2,3,4,5,6,7,8,52,53,59,62,68,70,74,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-14,-11,-10,-13,-12,]),'DATABASE':([9,25,30,37,40,50,69,],[14,34,39,51,54,58,71,]),'COLLECTION':([9,13,29,48,60,64,72,],[15,20,38,56,65,67,73,]),'LBRACE':([10,12,13,49,],[16,18,19,57,]),'DOCUMENTS':([11,],[17,]),'IDENTIFIER':([14,15,20,34,38,39,51,54,56,58,65,67,71,73,],[21,22,28,48,52,53,59,60,62,64,68,70,72,74,]),'STRING':([16,18,19,32,33,55,57,],[24,24,24,41,42,42,24,]),'FROM':([17,28,36,],[25,37,50,]),'WITH':([21,],[29,]),'INTO':([22,31,66,],[30,40,69,]),'RBRACE':([23,26,27,42,43,44,45,46,47,61,63,],[31,35,36,-17,-15,-18,-19,-20,-21,-16,66,]),'COMMA':([23,26,27,42,43,44,45,46,47,61,63,],[32,32,32,-17,-15,-18,-19,-20,-21,-16,32,]),'COLON':([24,41,],[33,55,]),'NUMBER':([33,55,],[44,44,]),'TRUE':([33,55,],[45,45,]),'FALSE':([33,55,],[46,46,]),'NULL':([33,55,],[47,47,]),'WHERE':([35,],[49,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'create_db':([0,],[2,]),'create_collection':([0,],[3,]),'insert_document':([0,],[4,]),'get_documents':([0,],[5,]),'update_document':([0,],[6,]),'delete_document':([0,],[7,]),'delete_collection':([0,],[8,]),'document':([16,18,19,57,],[23,26,27,63,]),'value':([33,55,],[43,61,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> create_db','statement',1,'p_statement','analizer.py',70),
  ('statement -> create_collection','statement',1,'p_statement','analizer.py',71),
  ('statement -> insert_document','statement',1,'p_statement','analizer.py',72),
  ('statement -> get_documents','statement',1,'p_statement','analizer.py',73),
  ('statement -> update_document','statement',1,'p_statement','analizer.py',74),
  ('statement -> delete_document','statement',1,'p_statement','analizer.py',75),
  ('statement -> delete_collection','statement',1,'p_statement','analizer.py',76),
  ('create_db -> CREATE DATABASE IDENTIFIER WITH COLLECTION IDENTIFIER','create_db',6,'p_create_db','analizer.py',80),
  ('create_collection -> CREATE COLLECTION IDENTIFIER INTO DATABASE IDENTIFIER','create_collection',6,'p_create_collection','analizer.py',84),
  ('insert_document -> INSERT LBRACE document RBRACE INTO DATABASE IDENTIFIER COLLECTION IDENTIFIER','insert_document',9,'p_insert_document','analizer.py',88),
  ('get_documents -> GET DOCUMENTS FROM DATABASE IDENTIFIER COLLECTION IDENTIFIER','get_documents',7,'p_get_documents','analizer.py',92),
  ('update_document -> UPDATE LBRACE document RBRACE WHERE LBRACE document RBRACE INTO DATABASE IDENTIFIER COLLECTION IDENTIFIER','update_document',13,'p_update_document','analizer.py',96),
  ('delete_document -> DELETE LBRACE document RBRACE FROM DATABASE IDENTIFIER COLLECTION IDENTIFIER','delete_document',9,'p_delete_document','analizer.py',100),
  ('delete_collection -> DELETE COLLECTION IDENTIFIER FROM DATABASE IDENTIFIER','delete_collection',6,'p_delete_collection','analizer.py',104),
  ('document -> STRING COLON value','document',3,'p_document','analizer.py',108),
  ('document -> document COMMA STRING COLON value','document',5,'p_document','analizer.py',109),
  ('value -> STRING','value',1,'p_value','analizer.py',117),
  ('value -> NUMBER','value',1,'p_value','analizer.py',118),
  ('value -> TRUE','value',1,'p_value','analizer.py',119),
  ('value -> FALSE','value',1,'p_value','analizer.py',120),
  ('value -> NULL','value',1,'p_value','analizer.py',121),
]
